WebsiteChuyenDe1/Areas/Admin/Controllers/LoginAdminController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebsiteChuyenDe1.Models;
using WebsiteChuyenDe1.Areas.Admin.ModelAdmin;

namespace WebsiteChuyenDe1.Areas.Admin.Controllers
{

    [OutputCache(NoStore = true, Duration = 0, VaryByParam = "None")]
    public class LoginAdminController : Controller
    {
        dbnewEntities1 db = new dbnewEntities1();
        // GET: Admin/LoginAdmin
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult Reg()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Reg(Regmodel regmodel)
        {
            var data = db.AdminAccounts.ToList();
            if (ModelState.IsValid)
            {
                if (!(regmodel.PassWord.Equals(regmodel.ConfirmPassWord)))
                {
                    ViewBag.Message = "Mật khẩu xác nhận không khớp !!";
                    return View();
                }
                foreach (var item in data)
                {
                    if (item.TaiKhoan.Equals(regmodel.UserName))
                    {
                        ViewBag.Message = "Tài khoản đã tồn tại!!";
                        return View();
                    }
                }
                var dao = new adminDao();
                AdminAccount adminAccount = new AdminAccount();
                adminAccount.TaiKhoan = regmodel.UserName;
                adminAccount.MatKhau = HashMD5.MD5Hash( regmodel.PassWord);
                var res = dao.Insert(adminAccount);
                if (res ==2)
                {
                    /* ViewBag.Message = "Đăng ký thành công";
                     RedirectToAction("Index");*/
                    var resreg = dao.Login(regmodel.UserName, HashMD5.MD5Hash(regmodel.PassWord));
                    if (resreg)
                    {
                        var user = dao.GetById(regmodel.UserName);
                        var adminSession = new AdminLogin();
                        adminSession.AdminName = user.TaiKhoan;
                        /*userSession.UserID = user.id;*/
                        Session.Add(CommonConstants.ADMIN_SESSION, adminSession);
                        return RedirectToAction("Index", "Default");
                    }
                }
            }
            return View();
        }
        public ActionResult Login(LoginModel model)
        {
                if (ModelState.IsValid)
                {
                    var dao = new adminDao();
                    var res = dao.Login(model.UserName, HashMD5.MD5Hash(model.PassWord));
                    if (res)
                    {
                        var user = dao.GetById(model.UserName);
                        var adminSession = new AdminLogin();
                    adminSession.AdminName = user.TaiKhoan;
                    /*userSession.UserID = user.id;*/
                    Session.Add(CommonConstants.ADMIN_SESSION, adminSession);
                    return RedirectToAction("Index", "Default");
                    }
                    else
                    {
                    ViewBag.Message = "Thông tin đăng nhập không chính xác";
                    return View("Index");
                }
                }
            return View();
        }
        public ActionResult Logout()
        {
            Session.Clear();
            return RedirectToAction("Index");

        }
    }
}

WebsiteChuyenDe1/Areas/Admin/Views/LoginAdmin/Index.cshtml
@model WebsiteChuyenDe1.Areas.Admin.ModelAdmin.LoginModel

@{
    ViewBag.Title = "Đăng nhập hệ thống";
    Layout = "";
}
<!DOCTYPE html>
<html lang="zxx">
<head>
    <title>Đăng nhập hệ thống</title>
    <!-- custom-theme -->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta name="keywords" content="Esteem Responsive web template, Bootstrap Web Templates, Flat Web Templates, Android Compatible web template,
Smartphone Compatible web template, free webdesigns for Nokia, Samsung, LG, SonyEricsson, Motorola web design" />
    <script type="application/x-javascript">
        addEventListener("load", function() { setTimeout(hideURLbar, 0); }, false);
               function hideURLbar(){ window.scrollTo(0,1); } </script>
    <!-- //custom-theme -->
    <link href="~/Areas/Admin/Data/template/css/bootstrap.css" rel="stylesheet" type="text/css" media="all" />
    <link href="~/Areas/Admin/Data/template/css/snow.css" rel="stylesheet" type="text/css" media="all" />
    <link href="~/Areas/Admin/Data/template/css/component.css" rel="stylesheet" type="text/css" media="all" />
    <link href="~/Areas/Admin/Data/template/css/style_grid.css" rel="stylesheet" type="text/css" media="all" />
    <link href="~/Areas/Admin/Data/template/css/style.css" rel="stylesheet" type="text/css" media="all" />
    <!-- font-awesome-icons -->
    <link href="~/Areas/Admin/Data/template/css/font-awesome.css" rel="stylesheet">
    <!-- //font-awesome-icons -->
    <link href="//fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i,800" rel="stylesheet">
</head>
<body>
    <!-- /pages_agile_info_w3l -->

    <div class="pages_agile_info_w3l">
        <!-- /login -->
        <div class="over_lay_agile_pages_w3ls">
            <div class="registration">

                <div class="signin-form profile">
                    <h2>Sign in Form</h2>
                    <div class="login-form">
                        @using (Html.BeginForm("Login", "LoginAdmin", FormMethod.Post))
                        {
                            <input type="text" name="UserName" placeholder="Tài khoản" required="">
                            <input type="password" name="PassWord" placeholder="Password" required="">
                            <div class="tp">
                                <input type="submit" value="Đăng nhập">
                            </div>
                        }
                    </div>
                    <div class="login-social-grids">
                        <ul>
                            <li><a href="#"><i class="fa fa-facebook"></i></a></li>
                            <li><a href="#"><i class="fa fa-twitter"></i></a></li>
                            <li><a href="#"><i class="fa fa-rss"></i></a></li>
                        </ul>
                    </div>
                    <p><a href="@Url.Action("Reg","LoginAdmin")"> Đăng ký ngay?</a></p>
                </div>
            </div>
            <!--copy rights start here-->
            <div class="copyrights_agile">
                @if (ViewBag.Message != null)
                {
                    <div class="alert alert-danger">
                        @ViewBag.Message
                    </div>
                }
                <p>© 2017 Esteem. All Rights Reserved | Design by  <a href="http://w3layouts.com/" target="_blank">W3layouts</a> </p>
            </div>
            <!--copy rights end here-->
        </div>
    </div>
    <!-- /login -->
    <!-- //pages_agile_info_w3l -->
    <!-- js -->

    <script type="text/javascript" src="~/Areas/Admin/Data/template/js/jquery-2.1.4.min.js"></script>
    <script src="~/Areas/Admin/Data/template/js/modernizr.custom.js"></script>

    <script src="~/Areas/Admin/Data/template/js/classie.js"></script>
    <script src="~/Areas/Admin/Data/template/js/gnmenu.js"></script>
    <script>
        new gnMenu(document.getElementById('gn-menu'));
    </script>

    <!-- //js -->

    <script src="~/Areas/Admin/Data/template/js/screenfull.js"></script>
    <script>
        $(function () {
            $('#supported').text('Supported/allowed: ' + !!screenfull.enabled);

            if (!screenfull.enabled) {
                return false;
            }



            $('#toggle').click(function () {
                screenfull.toggle($('#container')[0]);
            });
        });
    </script>
    <script src="~/Areas/Admin/Data/template/js/jquery.nicescroll.js"></script>
    <script src="~/Areas/Admin/Data/template/js/scripts.js"></script>
    <script src="~/Areas/Admin/Data/template/js/snow.js"></script>
    <script type="text/javascript">

        var _gaq = _gaq || [];
        _gaq.push(['_setAccount', 'UA-36251023-1']);
        _gaq.push(['_setDomainName', 'jqueryscript.net']);
        _gaq.push(['_trackPageview']);

        (function () {
            var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
            ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
            var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
        })();

    </script>
    <script type="text/javascript" src="~/Areas/Admin/Data/template/js/bootstrap-3.1.1.min.js"></script>
</body>
</html>

WebsiteChuyenDe1/Areas/Admin/Views/LoginAdmin/Reg.cshtml
@model WebsiteChuyenDe1.Areas.Admin.ModelAdmin.Regmodel
@{
    ViewBag.Title = "Đăng ký tài khoản";
    Layout = "";
}
<!DOCTYPE html>
<html lang="zxx">
<head>
    <title>Esteem  An Admin Panel Category Flat Bootstrap Responsive Website Template | Sign Up :: w3layouts</title>
    <!-- custom-theme -->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta name="keywords" content="Esteem Responsive web template, Bootstrap Web Templates, Flat Web Templates, Android Compatible web template,
Smartphone Compatible web template, free webdesigns for Nokia, Samsung, LG, SonyEricsson, Motorola web design" />
    <script type="application/x-javascript">
        addEventListener("load", function() { setTimeout(hideURLbar, 0); }, false);
               function hideURLbar(){ window.scrollTo(0,1); } </script>
    <!-- //custom-theme -->
    <link href="~/Areas/Admin/Data/template/css/bootstrap.css" rel="stylesheet" type="text/css" media="all" />
    <link href="~/Areas/Admin/Data/template/css/snow.css" rel="stylesheet" type="text/css" media="all" />
    <link href="~/Areas/Admin/Data/template/css/component.css" rel="stylesheet" type="text/css" media="all" />
    <link href="~/Areas/Admin/Data/template/css/style_grid.css" rel="stylesheet" type="text/css" media="all" />
    <link href="~/Areas/Admin/Data/template/css/style.css" rel="stylesheet" type="text/css" media="all" />
    <!-- font-awesome-icons -->
    <link href="~/Areas/Admin/Data/template/css/font-awesome.css" rel="stylesheet">
    <!-- //font-awesome-icons -->
    <link href="//fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i,800" rel="stylesheet">
</head>
<body>
    <!-- /pages_agile_info_w3l -->

    <div class="pages_agile_info_w3l">
        <!-- /login -->
        <div class="over_lay_agile_pages_w3ls two">
            <div class="registration">

                <div class="signin-form profile">
                    <h2>Đăng ký tài khoản</h2>
                    <div class="login-form">
                        @using (Html.BeginForm("Reg", "LoginAdmin", FormMethod.Post))
                        {
                            <input type="text" name="UserName" placeholder="Username" required="">
                            <input type="password" name="PassWord" placeholder="Password" required="">
                            <input type="password" name="ConfirmPassWord" placeholder="Confirm Password" required="">

                            <div class="tp">
                                <input type="submit" value="Đăng ký">
                            </div>
                        }
                        </div>

                    <p><a href="#"> By clicking Sign Up, I agree to your terms</a></p>

                    <h6><a href="@Url.Action("Index","LoginAdmin")">Đăng nhập</a><h6>
                </div>
            </div>
            <!--copy rights start here-->
            <div class="copyrights_agile two">
                @if (ViewBag.Message != null)
                {
                    <div class="alert alert-danger">
                        @ViewBag.Message
                    </div>
                }
                <p>© 2017 Esteem. All Rights Reserved | Design by  <a href="http://w3layouts.com/" target="_blank">W3layouts</a> </p>
            </div>
            <!--copy rights end here-->
        </div>
    </div>
    <!-- /login -->
    <!-- //pages_agile_info_w3l -->
    <!-- js -->

    <script type="text/javascript" src="~/Areas/Admin/Data/template/js/jquery-2.1.4.min.js"></script>
    <script src="~/Areas/Admin/Data/template/js/modernizr.custom.js"></script>

    <script src="~/Areas/Admin/Data/template/js/classie.js"></script>
    <script src="~/Areas/Admin/Data/template/js/gnmenu.js"></script>
    <script>
        new gnMenu(document.getElementById('gn-menu'));
    </script>

    <!-- //js -->

    <script src="~/Areas/Admin/Data/template/js/screenfull.js"></script>
    <script>
        $(function () {
            $('#supported').text('Supported/allowed: ' + !!screenfull.enabled);

            if (!screenfull.enabled) {
                return false;
            }



            $('#toggle').click(function () {
                screenfull.toggle($('#container')[0]);
            });
        });
    </script>
    <script src="~/Areas/Admin/Data/template/js/jquery.nicescroll.js"></script>
    <script src="~/Areas/Admin/Data/template/js/scripts.js"></script>
    <script src="~/Areas/Admin/Data/template/js/snow.js"></script>
    <script type="text/javascript">

        var _gaq = _gaq || [];
        _gaq.push(['_setAccount', 'UA-36251023-1']);
        _gaq.push(['_setDomainName', 'jqueryscript.net']);
        _gaq.push(['_trackPageview']);

        (function () {
            var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
            ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
            var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
        })();

    </script>
    <script type="text/javascript" src="~/Areas/Admin/Data/template/js/bootstrap-3.1.1.min.js"></script>


</body>
</html>