WebsiteChuyenDe1/Models/AdminAccount.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebsiteChuyenDe1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AdminAccount
    {
        public string TaiKhoan { get; set; }
        public string MatKhau { get; set; }
    }
}

WebsiteChuyenDe1/Areas/Admin/Controllers/AdminAccountsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using WebsiteChuyenDe1.Models;

namespace WebsiteChuyenDe1.Areas.Admin.Controllers
{
    public class AdminAccountsController : BaseController
    {
        private dbnewEntities1 db = new dbnewEntities1();

        // GET: Admin/AdminAccounts
        public ActionResult Index()
        {
            return View(db.AdminAccounts.ToList());
        }

        // GET: Admin/AdminAccounts/Details/5
        public ActionResult Details(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            AdminAccount adminAccount = db.AdminAccounts.Find(id);
            if (adminAccount == null)
            {
                return HttpNotFound();
            }
            return View(adminAccount);
        }

        // GET: Admin/AdminAccounts/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Admin/AdminAccounts/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "TaiKhoan,MatKhau")] AdminAccount adminAccount)
        {
            var data = db.AdminAccounts.ToList();
            if (ModelState.IsValid)
            {
                foreach (var item in data)
                {
                    if (item.TaiKhoan.Equals(adminAccount.TaiKhoan))
                    {
                        ViewBag.Message = "Tên đăng nhập đã tồn tại!!";
                        return View();
                    }
                }
                adminAccount.MatKhau = HashMD5.MD5Hash(adminAccount.MatKhau);
                db.AdminAccounts.Add(adminAccount);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(adminAccount);
        }

        // GET: Admin/AdminAccounts/Edit/5
        public ActionResult Edit(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            AdminAccount adminAccount = db.AdminAccounts.Find(id);
            if (adminAccount == null)
            {
                return HttpNotFound();
            }
            return View(adminAccount);
        }

        // POST: Admin/AdminAccounts/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "TaiKhoan,MatKhau")] AdminAccount adminAccount)
        {
            var data = db.AdminAccounts.ToList();
            if (ModelState.IsValid)
            {
                foreach (var item in data)
                {
                    if (item.TaiKhoan.Equals(adminAccount.TaiKhoan))
                    {
                        ViewBag.Message = "Tên đăng nhập đã tồn tại!!";
                        return View();
                    }
                }
                adminAccount.MatKhau = HashMD5.MD5Hash(adminAccount.MatKhau);
                db.Entry(adminAccount).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(adminAccount);
        }

        // GET: Admin/AdminAccounts/Delete/5
        public ActionResult Delete(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            AdminAccount adminAccount = db.AdminAccounts.Find(id);
            if (adminAccount == null)
            {
                return HttpNotFound();
            }
            return View(adminAccount);
        }

        // POST: Admin/AdminAccounts/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(string id)
        {
            AdminAccount adminAccount = db.AdminAccounts.Find(id);
            db.AdminAccounts.Remove(adminAccount);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

WebsiteChuyenDe1/Areas/Admin/Views/AdminAccounts/Create.cshtml
@model WebsiteChuyenDe1.Models.AdminAccount

@{
    ViewBag.Title = "Create";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

<h2>Create</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>AdminAccount</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.TaiKhoan, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TaiKhoan, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TaiKhoan, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.MatKhau, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.MatKhau, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.MatKhau, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>
@if (ViewBag.Message != null)
{
    <div class="alert alert-danger">
        @ViewBag.Message
    </div>
}

WebsiteChuyenDe1/Areas/Admin/Views/AdminAccounts/Delete.cshtml
@model WebsiteChuyenDe1.Models.AdminAccount

@{
    ViewBag.Title = "Delete";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>AdminAccount</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.MatKhau)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MatKhau)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

WebsiteChuyenDe1/Areas/Admin/Views/AdminAccounts/Details.cshtml
@model WebsiteChuyenDe1.Models.AdminAccount

@{
    ViewBag.Title = "Details";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

<h2>Details</h2>

<div>
    <h4>AdminAccount</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.MatKhau)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MatKhau)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.TaiKhoan }) |
    @Html.ActionLink("Back to List", "Index")
</p>

WebsiteChuyenDe1/Areas/Admin/Views/AdminAccounts/Edit.cshtml
@model WebsiteChuyenDe1.Models.AdminAccount

@{
    ViewBag.Title = "Edit";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>AdminAccount</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.TaiKhoan)

        <div class="form-group">
            @Html.Label("Mật khẩu", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.MatKhau, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.MatKhau, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>
@if (ViewBag.Message != null)
{
    <div class="alert alert-danger">
        @ViewBag.Message
    </div>
}

WebsiteChuyenDe1/Areas/Admin/Views/AdminAccounts/Index.cshtml
@model IEnumerable<WebsiteChuyenDe1.Models.AdminAccount>

@{
    ViewBag.Title = "Index";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

    <h2 style="text-align:center;padding-top:1em">Thêm account admin</h2>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.TaiKhoan)
        </th>
        <th>
           
            @Html.DisplayNameFor(model => model.MatKhau)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
<tr>
    <td> @Html.DisplayFor(modelItem => item.TaiKhoan)</td>

    <td>

        @Html.DisplayFor(modelItem => item.MatKhau)
    </td>

    <td>
        <a href="@Url.Action( "Create","AdminAccounts")"><img src="~/images/edit_add.png" /></a>&emsp;
        <a href="@Url.Action( "Edit","AdminAccounts" ,new { id = item.TaiKhoan })"><img src="~/images/settings.png" /></a>&emsp;
        <a href="@Url.Action( "Delete","AdminAccounts", new { id = item.TaiKhoan })"><img src="~/images/delete.png" /></a>

    </td>
</tr>
}

</table>